name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'mc/*'

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tags from branch
        id: extract_tags
        run: |
          MC_VERSION="$(echo $GITHUB_REF | sed -e 's/refs\/heads\/mc\///' -e 's/refs\/heads\/main/latest/')"
          TAGS="TAGS=ghcr.io/usa-reddragon/papermc:$MC_VERSION"

          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
            TAGS="$TAGS,ghcr.io/usa-reddragon/papermc:$(grep 'ARG PAPER_BUILD' Dockerfile.paper | sed -e 's/ARG PAPER_BUILD=//')"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT
      - name: Build and push Paper
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile.paper
          tags: ${{ steps.extract_tags.outputs.TAGS }}
  fabric:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tag from branch
        id: extract_tag
        run: |
          # If the branch is "mc/1.20.1", this will extract "1.20.1"
          # if the branch is "main", this will extract "latest"
          echo "TAG=$(echo $GITHUB_REF | sed -e 's/refs\/heads\/mc\///' -e 's/refs\/heads\/main/latest/')" >> $GITHUB_OUTPUT
      - name: Build and push Fabric
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile.fabric
          tags: ghcr.io/usa-reddragon/fabric:${{ steps.extract_tag.outputs.TAG }}
