name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Paper
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile.paper
          tags: ghcr.io/usa-reddragon/papermc:latest
  fabric:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Fabric
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile.fabric
          tags: ghcr.io/usa-reddragon/fabric:latest
