name: Test Docker Build

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pr-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Paper
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./Dockerfile.paper
  pr-fabric:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Fabric
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./Dockerfile.fabric
